# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: lqdev.PodcastTUI
PackageVersion: 1.10.0
InstallerType: zip
NestedInstallerType: portable
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: podcast-tui-v1.10.0-windows-aarch64\podcast-tui.exe
    PortableCommandAlias: podcast-tui
  InstallerUrl: https://github.com/lqdev/podcast-tui/releases/download/v1.10.0/podcast-tui-v1.10.0-windows-aarch64.zip
  InstallerSha256: PLACEHOLDER_UPDATE_AFTER_CI_BUILD
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: podcast-tui-v1.10.0-windows-x86_64\podcast-tui.exe
    PortableCommandAlias: podcast-tui
  InstallerUrl: https://github.com/lqdev/podcast-tui/releases/download/v1.10.0/podcast-tui-v1.10.0-windows-x86_64.zip
  InstallerSha256: PLACEHOLDER_UPDATE_AFTER_CI_BUILD
ManifestType: installer
ManifestVersion: 1.10.0
